// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WEB_KEY',
      defaultValue: 'KEY_NOT_FOUND',
    ),
    appId: '1:445062815461:web:43a87e113170e271fc7e0c',
    messagingSenderId: '445062815461',
    projectId: 'collectors-app-911b4',
    authDomain: 'collectors-app-911b4.firebaseapp.com',
    storageBucket: 'collectors-app-911b4.firebasestorage.app',
    measurementId: 'G-PQMYMZL084',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_ANDROID_KEY',
      defaultValue: 'KEY_NOT_FOUND',
    ),
    appId: '1:445062815461:android:10714ad83d6309f0fc7e0c',
    messagingSenderId: '445062815461',
    projectId: 'collectors-app-911b4',
    storageBucket: 'collectors-app-911b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_IOS_KEY',
      defaultValue: 'KEY_NOT_FOUND',
    ),
    appId: '1:445062815461:ios:9f6a5955dcf0abbdfc7e0c',
    messagingSenderId: '445062815461',
    projectId: 'collectors-app-911b4',
    storageBucket: 'collectors-app-911b4.firebasestorage.app',
    iosBundleId: 'com.example.collectorsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_MACOS_KEY',
      defaultValue: 'KEY_NOT_FOUND',
    ),
    appId: '1:445062815461:ios:9f6a5955dcf0abbdfc7e0c',
    messagingSenderId: '445062815461',
    projectId: 'collectors-app-911b4',
    storageBucket: 'collectors-app-911b4.firebasestorage.app',
    iosBundleId: 'com.example.collectorsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WINDOWS_KEY',
      defaultValue: 'KEY_NOT_FOUND',
    ),
    appId: '1:445062815461:web:75858e4066a83e46fc7e0c',
    messagingSenderId: '445062815461',
    projectId: 'collectors-app-911b4',
    authDomain: 'collectors-app-911b4.firebaseapp.com',
    storageBucket: 'collectors-app-911b4.firebasestorage.app',
    measurementId: 'G-1084Q25YVN',
  );
}
